feat: add authentication and authorization service
jan-zabloudil/release-manager pull request #16
Opened 2024-04-01 00:19 UTC by jan-zabloudil

This PR introduces several changes related to auth and users:

- Authentication and authorization were completely moved to the service layer. 
- Users are not read directly from `auth.users`; Instead, a `public users` table was added (as [recommended by Supabase](https://supabase.com/docs/guides/auth/managing-user-data)). This approach is more convenient because working directly with `auth.users` is not ideal; it cannot be used in joins (you need to write a PostgreSQL functions).
-  Tests have been added for the user and auth service.

2024-04-02 12:30 UTC, CermakM commented on repository/errors/auth.go
> +			return fmt.Errorf("%w: %s", svcerr.ErrAuthenticationFailed, err.Error())
Here I guess you use the `NewAuthErr(message)` function mentioned in the previous comment.

2024-04-02 12:30 UTC, CermakM commented on repository/errors/user.go
> +	var postgreErr *postgrestgo.RequestError
Why error from this package?

2024-04-02 12:30 UTC, CermakM commented on transport/utils/context.go
Singular name of the package.

2024-04-02 12:30 UTC, CermakM commented on repository/utils/utils.go
Singular name.

2024-04-02 12:30 UTC, CermakM commented on transport/model/user.go
Please, change the `ToNetUser` function names as well, I believe `ToUser` or `ToUserFromFields` should do well.

2024-04-02 15:52 UTC, jan-zabloudil commented on repository/error/error.go
I see repository errors are causing lot of confusion. I simplified the whole logic.

In supabase client you can access:
- `Auth` that returns *supabase.ErrorResponse
- `DB` that returns postgres errors (*postgrestgo.RequestError)
- `Admin` (for working with auth.users) that return *supabase.ErrorResponse 

A separate function is defined to map errors for each case to service errors.

2024-04-02 15:52 UTC, jan-zabloudil commented on repository/error/error.go
> +		case 401, 404:
In case of Auth - both 401, 404 errors means authentication failed (token is not valid or user does not exist anymore)

2024-04-02 15:52 UTC, jan-zabloudil commented on repository/error/error.go
> +		case 404:
In Admin (which I use only for DELETE /admin/users/{id}) error 404 means that user was not found. I dont want to map any other error to service errors.

2024-04-02 15:52 UTC, jan-zabloudil commented on service/error/error.go
I also simplified /service/error/error.go

I dont create specific error for each entity (such as `ErrUserNotFound`, `ErrProjectNotFound`). Instead, I have just  `ErrResourceNotFound`. Let me know if that is ok with you or if I should have specific error for each.

2024-04-02 15:52 UTC, jan-zabloudil commented on service/model/user.go
Instead of having function `ToSvcUser` in `repository/model`. I added service function `ToUser` which is responsible for creating valid user from params. 

I use name `ToUser`, because `NewUser` would be used if function actually creates a new user. 

So the approach is basically:
-  You can create directly user with user role of any string (because user role is now `type UserRole string`). Implementation is not hidden behind interfaces.
- But service functions `NewUserRole` or `ToUser` are provided and you should use them in order to be sure valid objects are created.

2024-04-02 15:56 UTC, jan-zabloudil commented
Some changes suggested in this PR are relevant for other open PRs as well. I am going to update them once this PR is approved.

2024-04-04 07:02 UTC, CermakM commented on service/error/error.go
It's often the case that you need to call multiple db calls in a single request, reading multiple resources. For example, assume you call products/{id} endpoint and get `ERR_RESOURCE_NOT_FOUND`, of course you assume it's the product that's missing. However, if the service layer has to perform multiple DB calls to retrieve the product, the client will never find out which of them was the issue.

2024-04-04 07:02 UTC, CermakM commented on service/model/user.go
I like this approach 👍

2024-04-04 07:18 UTC, CermakM requested changes

2024-04-04 07:18 UTC, CermakM commented on repository/error/error.go
> +func ToSvceErrFromAdmin(err error) error {
```suggestion
func ToSvcErrFromAdmin(err error) error {
```

2024-04-04 07:18 UTC, CermakM commented on repository/error/error.go
I believe a better way would be to define a custom Error type for repository layer and one for API layer and then translate that type to a status code based on the code stored in the error. Meaning for example in the pkg/dberror, you would have an `Error` model that might look something like this:
```go
type Error struct {
    code string
    message string
    err error
}
```

The `dberrors` (note that there is 's' at the end, customary for errors) package could define just an `IsNotFound` (no specific resource needed) because the service layer would check if it's `IsNotFound` and translate that into for example `New<resource>NotFoundErr(...)` again with a custom code (a suitable place for such errors could be pkg/apierrors. Similarly the transport layer would translate the service error to a suitable status code.

2024-04-04 17:29 UTC, jan-zabloudil commented on repository/user.go
> +	}
```
u, err := svcmodel.ToUser(
...
)
```

Returns service error, but I want to return a repository error indicating that the database data could not be converted to the service model (with details provided by that service error).

2024-04-05 06:16 UTC, jan-zabloudil commented on service/svcerrors/user.go
> +	return newUserUnknownErr(err)
If an error is not translated into a specific service error, I still want to return` <resource>UnknownError` to identify the service where the error occurred.

2024-04-08 11:46 UTC, CermakM commented on repository/dberrors/dberrors.go
> +func NewDBErrFromAuth(err error) error {
Does not return `DBError`

2024-04-08 11:46 UTC, CermakM commented on repository/dberrors/dberrors.go
> +func NewDBErr(err error) error {
```suggestion
func NewDBError(err error) error {
```

2024-04-08 11:46 UTC, CermakM commented on service/svcerrors/svcerrors.go
> +type RepositoryError interface {
This is nice, that could work nicely!

2024-04-09 06:30 UTC, jan-zabloudil commented on repository/user.go
> +			case "PGRST116":
Will be moved to helper function

2024-04-09 06:30 UTC, jan-zabloudil commented on transport/user.go
> +		switch {
Will be moved to helper function

2024-04-09 06:47 UTC, jan-zabloudil commented on transport/response.go
I will keep only Write methods in transport/response.

And the rest will be put into `pkg/response_errors`

2024-04-10 05:34 UTC, jan-zabloudil commented on transport/util/errormapper.go
I was struggling with the decision of where to place `ToResponseError`. Perhaps you have a better idea. thank you

2024-04-10 19:10 UTC, CermakM approved these changes

2024-04-11 05:25 UTC, merged