feat: add slack integration
jan-zabloudil/release-manager pull request #46
Opened 2024-05-06 07:57 UTC by jan-zabloudil

This PR introduces the ability to send Slack messages from the app in the following format: message + [message attachment](https://api.slack.com/reference/messaging/attachments)

<img width="574" alt="Snímek obrazovky 2024-05-06 v 9 51 58" src="https://github.com/jan-zabloudil/release-manager/assets/81581922/8b101200-5ac4-45b9-b23f-da18ed9323eb">

2024-05-07 06:15 UTC, jan-zabloudil commented on service/service.go
> +	GetSlackSettings(ctx context.Context) (settings model.SlackSettings, err error)
As suggested in #37, it might be better to have `GetSlackToken(ctx context.Context) (string, error)`.

2024-05-07 17:51 UTC, bolshakoff requested changes
Again, similar to GitHub, now it seems overcomplicated.

I'd find it much more smooth and sharp if you simply had a top-level `slack` package with `client` and `mock`, and simply have `SlackClient` whenever it is needed.

Where to have the msg model? If it doesn't have anything Slack-specific, then in domain, otherwise in Slack.. But overall, doesn't seem to be a big deal...

2024-05-07 17:51 UTC, bolshakoff commented on pkg/slack/client.go
> +package slack
I presume similarly to `resend` this will be moved to a good old top-level package.

2024-05-13 10:26 UTC, jan-zabloudil commented
To keep PR small, only `SlackClient` is added. Later on, client will be used in `ReleaseService`. Release service will define interface 

```
type slackClient interface {
	SendReleaseNotification(ctx context.Context, token, channelID string, n model.ReleaseNotification)
}
```

2024-05-13 10:39 UTC, jan-zabloudil commented on service/model/release.go
> +}
More fields will be added once the whole release functionality is implemented.

2024-05-13 10:39 UTC, jan-zabloudil commented on service/model/project.go
> +	ShowReleaseNotes bool
Fields in `ReleaseNotificationConfig` were renamed to match fields in Release model.

2024-05-13 11:42 UTC, bolshakoff approved these changes

2024-05-13 15:48 UTC, merged